import { Metadata } from 'next';

export const metadata: Metadata = {
  title: {
    default: 'Next js Default Title',
    template: '%s | codevolution',
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <header
          style={{
            backgroundColor: 'lightblue',
            padding: '1rem',
          }}
        >
          <h1>Header</h1>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: 'palegreen',
            padding: '1rem',
          }}
        >
          <h4>Footer</h4>
        </footer>
      </body>
    </html>
  );
}
